### PR TITLE
add support for docker-compose

### PR DESCRIPTION
**Pull request by Ratismal**
This PR configures the various containers for use with docker-compose, to allow for easier setup and execution. See the readme entry:

# Running everything through docker-compose

Experimentally, you can set everything up through docker-compose, which greatly reduces the complexity of setup.

There are two commands you have to run before using docker-compose:
```
docker pull nabcrr/sagemaker-rl-tensorflow:console
docker tag nabcrr/sagemaker-rl-tensorflow:console 520713654638.dkr.ecr.us-east-1.amazonaws.com/sagemaker-rl-tensorflow:coach0.11-cpu-py3
```

This pulls nabcrr's sagemaker and labels it as amazon's. The reason this is required is that rl_coach spawns its own docker instances of the amazon tagged container, which is locked behind authentication. Solution: fool it into thinking nabcrr's container is the real one!

Next, create an `.env` file that will be passed into all the docker containers. You can just copy over `.env.example`.

Afterwards, run:
```
docker-compose up
```

This will pull and build the required containers. You will get an issue with S3 because the minio bucket hasn't been created - you'll have to create the bucket and copy the custom_files as described in the minio tutorial above. By default, the data directory will be exposed to `.minio` for your convenience.

Once the bucket is set up, kill any active docker containers and run `docker-compose up` again.

## Gotchas

rl_coach relies on dynamically spawning more docker containers. We handle this by using sibling containers - we mount `//var/run/docker.sock:/var/run/docker.sock` as a volume. However, when shutting down docker-compose, these sibling containers don't get killed, so you have to manually clean them up.

Additionally, due to the nature of sibling volume bindings, the sagemaker container doesn't actually get bound to rl_coach - it gets bound to the base system. This means that (by default) docker will bind the directory to `/robo/container` to your base filesystem, as that's where sagemaker would expect them to be on rl_coach.

Finally, `//var/run/docker.sock:/var/run/docker.sock` is for windows. You may need to use `/var/run/docker.sock:/var/run/docker.sock` on unix systems.

### CODE REVIEW

**Comment by crr0004** [comment]
Just letting you know I'm reviewing this. It's an interesting approach. I'm
definitely open to having different ways of using the stack, as long as
they don't break each other.

The current way definitely needs improvement, especially starting and
stopping multiple containers and having the Sagemaker sdk control one.
That's just silly for a lot of cases.

Tomorrow (UTC+10) I will do a full thought dump for you.

**Comment by crr0004** [comment]
Sorry about taking so long to do this. I got pretty distracted with work and getting my own models running.

The ideal solution to this problem of having two containers running manually is to improve the usage of sagemaker-python-sdk so we launch the containers through the generated docker-compose file. The SDK is only a wrapper around docker and AWS service clients, although a [local mode is supported](https://github.com/crr0004/sagemaker-python-sdk/tree/62e959521445c880e04cd22b2dc9183c18f409ba/src/sagemaker/local).

The reason I kind of hacked around with having the robomaker start through a docker run command is because I didn't want to have to interact with the AWS robomaker client, especially because it's not meant for launching instances locally. Ideally it would all go through the python file.

**Comment by daj** [comment]
https://github.com/alexschultz/deepracer-for-dummies uses Docker Compose, so it's probably worth checking that repo before anybody works on this issue.

**Comment by breadcentric** [comment]
Taken into account that the go-to solution for docker-compose is https://github.com/aws-deepracer-community/deepracer-for-cloud, I'm closing this PR. Thank you for raising it for discussion @Ratismal

**Pull request closed without merging**
